### ISSUE TITLE
Seminário2_revDartagnan

### ISSUE THREAD

**Issue by ddfarias** [cineasthales/Gifty#5]
* Lista de presentes é vinculada a algum site de vendas? Como o gifty identifica que um presente foi comprado?
* Para convidar alguém, esse alguém precisa estar na lista de amigos?

**Comment by cineasthales** [comment]
1) A API do Mercado Livre é utilizada para a busca de itens e para o sistema de recomendação. A marcação do item como comprado depende do convidado marcar diretamente na lista, no Gifty.
2) Sim, mas o sistema vai permitir convite para cadastro por email.
